### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lauraseidler** [ninety-six/fratomic#1]
Hi, 

just stumbled upon this by accident, and it looks right up our alley - would love to give it a spin!

I'm not seeing any License though - CAN we actually use this?

Would be awesome! 

(The same goes for mono-fractal, I think)

**Comment by benaccent** [comment]
Yes, feel free to use the starter project.

It'd be great to see how you use it and build upon it :-)

**Comment by benaccent** [comment]
License documentation has now been added as part of v1.0.2
